### ISSUE TITLE
Android 手机右上角按钮点击无反应，安卓 7.0，uc v11.6

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/blog#6]
@natforum

**Comment by rosuH** [comment]
@xcatliu 不只是 Android。
Win10 下 Edge 也无法点击右上角。
console 提示如下：

```
HTML1300: 进行了导航。
blog.rosuh.me
HTML1512: 不匹配的结束标记。
blog.rosuh.me (127,25)
HTML1508: 不匹配的结束标记。
blog.rosuh.me (192,1)
HTML1508: 不匹配的结束标记。
blog.rosuh.me (194,1)
HTML1509: 不匹配的结束标记。
blog.rosuh.me (196,1)
当前窗口: blog.rosuh.me
SCRIPT438: Object doesn't support property or method 'forEach'
theme.js (31,3)

```

![snipaste_2017-09-27_22-51-43](https://user-images.githubusercontent.com/15865017/30920417-73073b96-a3d6-11e7-83a7-974a89f9984d.png)

**Comment by xcatliu** [comment]
@rosuH 非常感谢提供错误信息，应该是 querySelectorAll 的返回值没有 forEach 方法：
https://css-tricks.com/snippets/javascript/loop-queryselectorall-matches/

**Comment by xcatliu** [comment]
Fixed in https://github.com/xcatliu/blog/commit/e5243652c737801265babd933e5a0123fd416318#diff-d694e656cf9ce57e04f51ebcb2a137feR31
