### ISSUE TITLE
将主题提取为独立仓库

### ISSUE THREAD

**Issue by rosuH** [xcatliu/blog#7]
请问这个主题会独立成为一个项目出来吗？便于更新和维护？
因为现在不知道如何才能**快速地**更新主题。（智商捉鸡...
目前是 clone 你的仓库，然后一个个文件搬过去... @_@

-----
感谢~

**Comment by xcatliu** [comment]
本来为了偷懒就没有提取为独立仓库，看来还是有需求呀，那我会尽快提取出来的
